services:
  - type: web
    name: blog-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python blog_api/manage.py collectstatic --noinput && python blog_api/manage.py migrate --noinput
    startCommand: gunicorn blog.wsgi:application --chdir blog_api --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
